---

- name: Merge List Dictionaries in Vars
  hosts: localhost

  vars_files:
    - ./vars/custom.yml
    - ./vars/delta.yml
    - ./vars/standard.yml

  tasks:
    - name: Print Values
      ansible.builtin.debug:
        msg: bla bla bla {{ list }}

    - name: Set_fact merged vars
      ansible.builtin.set_fact:
        data: "{{ [list1, list2, list3] | community.general.lists_mergeby('name', recursive=true, list_merge='append') }}"
        