---

# https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6

  # https://galaxy.ansible.com/docs/using/installing.html
  - src: https://github.com/bennojoy/nginx
    version: master
    name: nginx_role

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.3
    source: https://galaxy.ansible.com
