---

name: Ansible Lint By reviewdog
on: [pull_request]
jobs:
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ansible-lint
        uses: reviewdog/action-ansiblelint@v1.6.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review    # Change reporter.
          # ansiblelint_flags: '-x core .'
          ansiblelint_version: 6.17.0
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review    # Change reporter.
          # yamllint_flags: 'src/'
